site_name: Nethereum
theme: readthedocs
pages:
- 'Home' : 'index.md'
- 'Get Started with Nethereum' : 'getting-started.md'
- 'Nugets' : 'nugets.md'
- 'Transferring Ether' : 'nethereum-transferring-ether.md'
- 'Smart Contracts Interaction' : 'nethereum-smartcontrats-gettingstarted.md'
- 'Smart contracts Events / Logs / Filters' : 'nethereum-events-gettingstarted.md'
- 'Managing Accounts Nethereum' : 'accounts.md'
- 'Code generation':
    - 'vs-code and console': 'nethereum-code-generation.md'
    - 'ABI based code generator' : 'nethereum-abi-autogen.md'
- 'Interactive Workbooks' :
    - 'Index' : 'Nethereum.Workbooks/docs/index.md'
    - 'Getting Started Test Chain' : 'Nethereum.Workbooks/docs/nethereum-gettingstarted-testchain.workbook'
    - 'Nethereum Getting Started Infura' : 'Nethereum.Workbooks/docs/nethereum-gettingstarted-infura.workbook'
    - 'Smart Contracts integration' : 'Nethereum.Workbooks/docs/nethereum-smartcontrats-gettingstarted.workbook'
    - 'Events, Logs and Filters' : 'Nethereum.Workbooks/docs/nethereum-events-gettingstarted.workbook'
    - 'Events polling' : 'Nethereum.Workbooks/docs/nethereum-eventdtos-getallchanges.workbook'
    - 'Chain Id Management' : 'Nethereum.Workbooks/docs/Nethereum-ChainID-Management.workbook'
    - 'Unit conversion' : 'Nethereum.Workbooks/docs/nethereum-converting-units.workbook'
    - 'Getting Started With Smart Contracts (untyped)' : 'Nethereum.Workbooks/docs/nethereum-smartcontrats-untyped.workbook'
    - 'Managing nonces' : 'Nethereum.Workbooks/docs/nethereum-managing-nonces.workbook'
    - 'Using Nethereum managed accounts' : 'Nethereum.Workbooks/docs/nethereum-managed-accounts.workbook/index.workbook'
    - 'Creating a new Account using Geth Personal Api' : 'Nethereum.Workbooks/docs/nethereum-creating-a-new-account-using-geth.workbook'
- 'Unity 3d':
    - 'Sending Ether' : 'unity3d-sending-ether.md'
    - 'Smart contract interaction' : 'unity3d-smartcontracts-getting-started.md'
- 'Ethereum clients':
    - 'Introduction' : 'ethereum-and-clients/index.md'
    - 'Geth (Go client)' : 'ethereum-and-clients/geth.md'
    - 'Parity' : 'ethereum-and-clients/parity.md'
    - 'Quorum' : 'ethereum-and-clients/quorum.md'
    - 'Azure BaaS' : 'azure/set-up-blockchain-on-azure.md'
    - 'TestRPC' : 'ethereum-and-clients/test-rpc.md'
    - 'Ganache CLI' : 'ethereum-and-clients/ganache-cli.md'
    - 'Choosing a chain for development' : 'ethereum-and-clients/choosing-a-chain-for-development.md'
- 'Other tooling':
    - 'Kaleido': 'kaleido-and-nethereum.md'
- 'Web3 and RPC':
    - 'Web3' : 'introduction/web3.md'
    - 'RPC' : 'introduction/rpc.md'
    - 'IPC' : 'introduction/ipc.md'
- 'Smart Contracts untyped':
    - 'Create and deploy contracts' : 'contracts/deploying.md'
    - 'Calls, transactions, events, filters and topics' : 'contracts/calling-transactions-events.md'
    - 'Multiple output parameters and function DTOs' : 'contracts/functiondtos.md'
